<?php
  $banks =
      array (
              0 =>
                  array (
                      'name' => 'Access Bank',
                      'slug' => 'access-bank',
                      'code' => '044',
                      'longcode' => '044150149',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 1,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              1 =>
                  array (
                      'name' => 'Citibank Nigeria',
                      'slug' => 'citibank-nigeria',
                      'code' => '023',
                      'longcode' => '023150005',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 2,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              2 =>
                  array (
                      'name' => 'Diamond Bank',
                      'slug' => 'diamond-bank',
                      'code' => '063',
                      'longcode' => '063150162',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 3,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              3 =>
                  array (
                      'name' => 'Ecobank Nigeria',
                      'slug' => 'ecobank-nigeria',
                      'code' => '050',
                      'longcode' => '050150010',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 4,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              4 =>
                  array (
                      'name' => 'Enterprise Bank',
                      'slug' => 'enterprise-bank',
                      'code' => '084',
                      'longcode' => '084150015',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 5,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              5 =>
                  array (
                      'name' => 'Fidelity Bank',
                      'slug' => 'fidelity-bank',
                      'code' => '070',
                      'longcode' => '070150003',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 6,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              6 =>
                  array (
                      'name' => 'First Bank of Nigeria',
                      'slug' => 'first-bank-of-nigeria',
                      'code' => '011',
                      'longcode' => '011151003',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 7,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              7 =>
                  array (
                      'name' => 'First City Monument Bank',
                      'slug' => 'first-city-monument-bank',
                      'code' => '214',
                      'longcode' => '214150018',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 8,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              8 =>
                  array (
                      'name' => 'Guaranty Trust Bank',
                      'slug' => 'guaranty-trust-bank',
                      'code' => '058',
                      'longcode' => '058152036',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 9,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              9 =>
                  array (
                      'name' => 'Heritage Bank',
                      'slug' => 'heritage-bank',
                      'code' => '030',
                      'longcode' => '030159992',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 10,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              10 =>
                  array (
                      'name' => 'Keystone Bank',
                      'slug' => 'keystone-bank',
                      'code' => '082',
                      'longcode' => '082150017',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 11,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              11 =>
                  array (
                      'name' => 'MainStreet Bank',
                      'slug' => 'mainstreet-bank',
                      'code' => '014',
                      'longcode' => '014150331',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 12,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              12 =>
                  array (
                      'name' => 'Skye Bank',
                      'slug' => 'skye-bank',
                      'code' => '076',
                      'longcode' => '076151006',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 13,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              13 =>
                  array (
                      'name' => 'Stanbic IBTC Bank',
                      'slug' => 'stanbic-ibtc-bank',
                      'code' => '221',
                      'longcode' => '221159522',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 14,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              14 =>
                  array (
                      'name' => 'Standard Chartered Bank',
                      'slug' => 'standard-chartered-bank',
                      'code' => '068',
                      'longcode' => '068150015',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 15,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              15 =>
                  array (
                      'name' => 'Sterling Bank',
                      'slug' => 'sterling-bank',
                      'code' => '232',
                      'longcode' => '232150016',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 16,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              16 =>
                  array (
                      'name' => 'Union Bank of Nigeria',
                      'slug' => 'union-bank-of-nigeria',
                      'code' => '032',
                      'longcode' => '032080474',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 17,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              17 =>
                  array (
                      'name' => 'United Bank For Africa',
                      'slug' => 'united-bank-for-africa',
                      'code' => '033',
                      'longcode' => '033153513',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 18,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              18 =>
                  array (
                      'name' => 'Unity Bank',
                      'slug' => 'unity-bank',
                      'code' => '215',
                      'longcode' => '215154097',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 19,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              19 =>
                  array (
                      'name' => 'Wema Bank',
                      'slug' => 'wema-bank',
                      'code' => '035',
                      'longcode' => '035150103',
                      'gateway' => 'etz',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 20,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
              20 =>
                  array (
                      'name' => 'Zenith Bank',
                      'slug' => 'zenith-bank',
                      'code' => '057',
                      'longcode' => '057150013',
                      'gateway' => '',
                      'active' => true,
                      'is_deleted' => NULL,
                      'id' => 21,
                      'createdAt' => '2016-07-14T10:04:29.000Z',
                      'updatedAt' => '2016-07-14T10:04:29.000Z',
                  ),
          );

//    $bank = var_dump(json_decode($banks, true));
    $bank = json_encode($banks);

    echo $bank;

?>